### ISSUE TITLE
How to write a good README

### ISSUE THREAD

**Issue by memoriaJ** [cosmos-io/startup#35]
README.md 의 콘텐츠 구성, 작성법 등을 정리합니다. 
(참고: https://github.com/docker/docker/blob/master/README.md)

**Comment by memoriaJ** [comment]
README의 역할
---------------------
README는 프로젝트의 얼굴이다. Github에서는 각 저장소 방문 시 README.MD를 읽어 제일 먼저 보여준다. 방문자가 저장소의 목적을 이해할 수 있도록, README는 회사, 제품, 프로젝트의 소개나 주의 사항 등 주요 정보를 축약해서 담아야 한다.



README의 구성
---------------------
주로 아래와 같은 정보를 포함한다. 

* 회사/프로젝트/제품의 이름과 목적
* 기술 및 서비스 개요(설치/실행법, 개발/배포 환경, 특징, 활용 예제)
* 업데이트 시 수정, 개선 사항
* 카피라이트와 라이선스
* 관련 프로젝트



자주 사용되는 MARKDOWN 기본 문법
------------------------------------------------
#### 1. 제목
등호(=)와 빼기(-)를 밑줄로 사용하거나, 해시 문자(#)를 줄 시작에 위치시킴으로써 다양한 글자 크기의 제목을 사용할 수 있다. 
```
H1: = 또는 #
H2: - 또는 ##
H3 ~ H6: # 갯수에 따라 달라진다. 
```

#### 2. 리스트
*, +, - 로 순서 없는 목록을 만들고, 숫자와 마침표로 번호매김한다. 
```
순서 없는 리스트: *, +, -
순서 있는 리스트: (숫자). (내용)
```

#### 3. 강조
별표(*)와 밑줄(_)을 활용한다. 
```bash
볼드(bold): **내용** or __내용__
기울임(italics): *내용* or _내용_
취소선(scratch): ~~내용~~
```

#### 4. 링크
두 가지 형식의 링크를 지원한다. 참고한 docker는 인라인 링크를 주로 사용한다. 참조 형식 활용 시 링크 정의는 문서 어디에나 위치시킬 수 있다.  
```
1. 인라인 링크: [링크명](url)
2. 참조 형식 링크
- 본문표시: [링크명][링크ID]
- 링크정의: [링크ID]: url
```

#### 5. 이미지 삽입
링크와 유사한 문법을 사용한다. 
```
1. 인라인 링크: ![이미지명](url)
2. 참조 형식
- 본문표시: ![이미지명][이미지ID]
- 이미지정의: [이미지ID]: url
```

#### 6. 코드 블록화 
일반 문단에서 역따옴표(`)로 코드를 블록화하고, 강조할 수 있다.
```
`코드`
```

**Comment by ghmlee** [comment]
네. 이정도 문법이면 충분합니다. :)
