### ISSUE TITLE
Jenkins, Travis CI, drone.io 등 비교

### ISSUE THREAD

**Issue by hanjaelee** [cosmos-io/startup#57]

**Comment by ghmlee** [comment]
@dongjujang 가 작업하도록 하죠.

**Comment by ghmlee** [comment]
We are trying to use both Jenkins and drone.io. In this time, Travis CI is too expensive. @dongjujang is going to prepare Dockerfiles for the latest Jenkins and drone.io.

**Comment by ghmlee** [comment]
@dongjujang 수고하셨습니다.
