### ISSUE TITLE
Showing customed statistical datas on GoogleMaps.

### ISSUE THREAD

**Issue by kiyeonkim** [cosmos-io/startup#66]
Using overlays in GoogleMaps Javascript v3 API

**Comment by kiyeonkim** [comment]
I have a problem with unintentional data showing in map.

**Comment by nikolaydubina** [comment]
I am not sure about the problem. Perhaps you alredy know this, but just in case, there is complement/substitute to google-maps - d3.js with topojson. those could be helpful

**Comment by kiyeonkim** [comment]
Your advice is helpful and I solved problem a moment ago. Thanks!
