### ISSUE TITLE
heroku 배포 튜토리얼

### ISSUE THREAD

**Issue by hanjaelee** [cosmos-io/startup#78]

**Comment by hanjaelee** [comment]
http://rorlab.gitbooks.io/railsguidebook/content/appendices/heroku.html 보고 학습하고 있습니다.

**Comment by ghmlee** [comment]
@hanjaelee Heroku에 Python 배포 다시 한 번 시도해보고 일감 닫아주세요.

**Comment by hanjaelee** [comment]
Github 와 연동해서 배포 해 봤습니다.
