### ISSUE TITLE
Dockerizing drone.io with Mysql

### ISSUE THREAD

**Issue by dongjujang** [cosmos-io/startup#86]
to setup database as mysql in dockerfile
https://drone.readthedocs.org/en/latest/content/setup/database/mysql/

**Comment by dongjujang** [comment]
I faced problem with memory of ec2
I cannot run mysql because memory of my ec2 instance is so small

**Comment by ghmlee** [comment]
@dongjujang try to t2.micro or http://stackoverflow.com/questions/1178736/mysql-maximum-memory-usage

**Comment by dongjujang** [comment]
@ghmlee thank you for your recommend, I'll try to t2.micro

**Comment by dongjujang** [comment]
I made a systemd file, named drone-cosmos.service

**Comment by dongjujang** [comment]
I'm not use mysql yet.
